[default]
SQLALCHEMY_DATABASE_URI = 'postgres://guwago:5ud2FPpF7mygAmzw9efeWqp1hpXbDyTi@dpg-clp8gi9oh6hc73burcsg-a/db_hsc'
SECRET_KEY = "secreto"
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_EXTENSIONS = ['.jpg','.png','.gif','.jpeg','.pdf']
UPLOAD_PATH = 'uploads'


MAIL_SERVER = "smtp.gmail.com"
MAIL_PORT = 587
MAIL_USE_TLS = true
MAIL_USE_SSL = false
MAIL_USERNAME = "chucrutis64@gmail.com"
MAIL_PASSWORD = "tffn xscl tcsi qjbx"
MAIL_DEFAULT_SENDER = "chucrutis64@gmail.com"
